//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.GenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.gen.com/", ConfigurationName="GenService.GenService")]
    public interface GenService {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément name de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.gen.com/GenService/SendDocumentOperationRequest", ReplyAction="http://facade.gen.com/GenService/SendDocumentOperationResponse")]
        WCF.GenService.SendDocumentOperationResponse SendDocumentOperation(WCF.GenService.SendDocumentOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.gen.com/GenService/SendDocumentOperationRequest", ReplyAction="http://facade.gen.com/GenService/SendDocumentOperationResponse")]
        System.Threading.Tasks.Task<WCF.GenService.SendDocumentOperationResponse> SendDocumentOperationAsync(WCF.GenService.SendDocumentOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocumentOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDocumentOperation", Namespace="http://facade.gen.com/", Order=0)]
        public WCF.GenService.SendDocumentOperationRequestBody Body;
        
        public SendDocumentOperationRequest() {
        }
        
        public SendDocumentOperationRequest(WCF.GenService.SendDocumentOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendDocumentOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key;
        
        public SendDocumentOperationRequestBody() {
        }
        
        public SendDocumentOperationRequestBody(string name, string content, string key) {
            this.name = name;
            this.content = content;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDocumentOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDocumentOperationResponse", Namespace="http://facade.gen.com/", Order=0)]
        public WCF.GenService.SendDocumentOperationResponseBody Body;
        
        public SendDocumentOperationResponse() {
        }
        
        public SendDocumentOperationResponse(WCF.GenService.SendDocumentOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendDocumentOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public SendDocumentOperationResponseBody() {
        }
        
        public SendDocumentOperationResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenServiceChannel : WCF.GenService.GenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenServiceClient : System.ServiceModel.ClientBase<WCF.GenService.GenService>, WCF.GenService.GenService {
        
        public GenServiceClient() {
        }
        
        public GenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF.GenService.SendDocumentOperationResponse WCF.GenService.GenService.SendDocumentOperation(WCF.GenService.SendDocumentOperationRequest request) {
            return base.Channel.SendDocumentOperation(request);
        }
        
        public bool SendDocumentOperation(string name, string content, string key) {
            WCF.GenService.SendDocumentOperationRequest inValue = new WCF.GenService.SendDocumentOperationRequest();
            inValue.Body = new WCF.GenService.SendDocumentOperationRequestBody();
            inValue.Body.name = name;
            inValue.Body.content = content;
            inValue.Body.key = key;
            WCF.GenService.SendDocumentOperationResponse retVal = ((WCF.GenService.GenService)(this)).SendDocumentOperation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF.GenService.SendDocumentOperationResponse> WCF.GenService.GenService.SendDocumentOperationAsync(WCF.GenService.SendDocumentOperationRequest request) {
            return base.Channel.SendDocumentOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF.GenService.SendDocumentOperationResponse> SendDocumentOperationAsync(string name, string content, string key) {
            WCF.GenService.SendDocumentOperationRequest inValue = new WCF.GenService.SendDocumentOperationRequest();
            inValue.Body = new WCF.GenService.SendDocumentOperationRequestBody();
            inValue.Body.name = name;
            inValue.Body.content = content;
            inValue.Body.key = key;
            return ((WCF.GenService.GenService)(this)).SendDocumentOperationAsync(inValue);
        }
    }
}
